version: "3.9"

services:
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/usr/src/ml-rest-api
    ports:
      - 8000:8000
    env_file: 
      - .env
    depends_on:
      - db
    networks:
      - ml-net
    image: app:django
    container_name: django_container

  db:
    image: postgres:latest
    # restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: 
      - .env
    environment:
      POSTGRES_DB: ml_project
      POSTGRES_USER: ata
      POSTGRES_PASSWORD: 1234567
    container_name: postgres_db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - ml-net

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sys/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - ml-net

networks:
  ml-net:
    driver: bridge




