version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.11.3
    steps:
      - checkout
      - run: python --version
      - run:
          name: Install apt-utils
          command: sudo apt-get update && sudo apt-get install -y apt-utils