
version: 2.1

jobs:
  build:
    # Primary container image where all commands run
    docker:
      - image: cimg/python:3.11.3
        environment:
          POSTGRES_DB: circle_test
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var
          
      - image: cimg/postgres:14.0
        name: db
        environment:
          PGHOST: cimg-postgres
          PGUSER: circleci
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client

      - run:
          name: Install apt-utils
          command: sudo apt-get update && sudo apt-get install -y apt-utils

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run database migrations
          command: |
            . venv/bin/activate
            python3 src/manage.py migrate
      
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            cd src
            python3 manage.py test

      - store_artifacts:
          path: test-reports/
          destination: python_app
      


