version: 2.1
jobs:
  build:
    docker:
      - image: python:3.9

    working_directory: ~/ML-REST-API

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Build Docker image
          command: |
            docker build -t ml-rest-api:latest src/

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - venv

  test:
    docker:
      - image: ml-rest-api:latest

    working_directory: ~/ML-REST-API

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            python manage.py test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
