# Generated by Django 4.2.1 on 2023-05-22 15:10

from django.db import migrations, models
import team_manager.managers


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', team_manager.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
